version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=django-insecure-s&zn1go+$19c=(waf8dz24dcv9civhwk-)jy8qzq*!(i$id2k*
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1,web
      - DATABASE_URL=postgres://hacker:hacker_pass@db:5432/hacking_portal
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - db
      - redis
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hacking_portal
      - POSTGRES_USER=hacker
      - POSTGRES_PASSWORD=hacker_pass
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
