# Generated by Django 6.0.7 on 2026-08-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='certifications',
            field=models.TextField(blank=True, help_text='e.g., OSCP, CEH, CompTIA Security+', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_verified_researcher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='skill_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], default='Beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='specialization',
            field=models.CharField(choices=[('Web Security', 'Web Security'), ('Network Security', 'Network Security'), ('Malware Analysis', 'Malware Analysis'), ('Cloud Security', 'Cloud Security'), ('OSINT', 'OSINT'), ('Cryptography', 'Cryptography'), ('Reverse Engineering', 'Reverse Engineering'), ('Binary Exploitation', 'Binary Exploitation')], default='Web Security', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
